### ISSUE TITLE
Missing libraries after Docker image compilation

### ISSUE THREAD

**Issue by leo-bart** [mbsim-env/build#2]
After compiling my local mbsim image using Docker, I'm getting missing libraries when trying to open the GUI applications. For instance, when running:

- mbsimgui:
```
leonardo@leo003:~/Software/mbsim-env-build$ ./local-docker/bin/mbsimgui 
./local-docker/bin/mbsimgui: error while loading shared libraries: libCoin.so.4.0.0: cannot open shared object file: No such file or directory
```
 - openmbv:
```
leonardo@leo003:~/Software/mbsim-env-build$ ./local-docker/bin/openmbv
./local-docker/bin/openmbv: error while loading shared libraries: libCoin.so.4.0.0: cannot open shared object file: No such file or directory
```
 - h5plotserie:
```
leonardo@leo003:~/Software/mbsim-env-build$ ./local-docker/bin/h5plotserie 
./local-docker/bin/h5plotserie: error while loading shared libraries: libhdf5.so.8: cannot open shared object file: No such file or directory
```

Also, all compilation steps and examples ran OK according to the `docker_build_report` and, in fact, if I go to the examples folders the executable `main` files are there, but I can't run them as well because they can't find `libmbsim.so.0`.

I have the missing libraries installed, so I could do some manual linking, but I understood that the Docker image was supposed to be self-contained.

**Edit** - I'm using the same shell where I ran `build.sh`

**Comment by friedrichatgc** [comment]
Yes, the docker image is self-contained, that's the aim of a docker image. A docker container is something like a virtual machine which is running on a docker image. Hence, you need to run any program which was build using this docker image inside of a corresponding docker container (a virtual machine), you cannot run any program build using the image on your local machine.
So you have to create a docker container from the docker image and inside from this container you can run `mbsimgui`, `openmbv`, ...
Since creating a docker container may be a bit complicate I have created helper scripts.
Please clearly follow https://github.com/mbsim-env/build/blob/master/README.md:
- add `<mypath>/build/docker/buildScripts` to your PATH
- run `mbsimxml`, `openmbv`, ... NOT `./local-docker/bin/mbsimgui` (this will run the corresponding scripts in `<mypath>/build/docker/buildScripts` which will create a docker container and run the corresponding program inside the container). 

See `<mypath>/build/docker/buildScripts` for any other program (make, gdb, ...) you can run. No other program can be run. If you need other programs to run you will have to add these to `<mypath>/build/docker/buildScripts` or start a docker container manually and "login" to this container.

Sure, the task of running a program inside a docker container is more complicated than running a program on the local machine but that's the price to pay. For this price you gain a mbsim build where you do not have to take care about library dependencies.

I tried to make starting the programs inside the docker container as easy as possible. Please see the script `<mypath>/build/docker/buildScripts/mbsbd` if you want to know how to start the docker container manually.

**Comment by leo-bart** [comment]
Got it!

I imagined that was something about Docker I wasn't understanding.

So that's my new output:
```shell
leonardo@leo003:~/Software/mbsim-env-build$ echo $PATH
/home/leonardo/Software/mbsim-env-build/build/docker/buildScripts:/usr/bin:/usr/local/bin:/home/leonardo/bin
leonardo@leo003:~/Software/mbsim-env-build$ openmbv
bash: /usr/local/mbsim-env/bin/openmbv: File or directory does not exist.
```
I supposed that maybe it was calling another `openmbv` instance I have installed, so I checked:
```bash
leonardo@leo003:~$ which openmbv
/home/leonardo/Software/mbsim-env-build/build/docker/buildScripts/openmbv
```
The calling path is, therefore, correct (apparently).

I have a theory that happens because when I compiled the docker build, I added `<mypath>/build/docker/buildScripts` to the *end* of my PATH, so I believe the build tools linked all libraries to my existing versions outside the Docker image, whose folders were prioritary in my PATH. Is that possible? Later today I'll try and recompile everything with only `<mypath>/build/docker/buildScripts` (and the usual `/usr/bin`, `/usr/local/bin` ...) on my PATH.

# Nightly Edit 
Just recompiled everything with a minimal PATH. All modules and examples built ok.

To test everything, I entered on the same shell I used to build de image:
`leonardo@leo003:~/Software/mbsim-env-build$ mbsimgui `

Which resulted in
```shell
QStandardPaths: wrong ownership on runtime directory /run/user/, 0 instead of 1000
process 12: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
  D-Bus not built with -rdynamic so unable to print a backtrace
/var/tmp/sclYOs86O: line 8:    12 Aborted                 (core dumped) PATH=/usr/lib64/ccache:$PATH mbsimgui
```
I googled the error and it seems the `QStandardPaths` may be a Qt bug in some cases.

**Comment by friedrichatgc** [comment]
I don't know any reason for your first error. I can just imagine that your path /home/leonardo/Software/mbsim-env-build may have some symbolic links in it which may cause trouble.

Pushing the path to the end of PATH should not harm if on other dirs exists in PATH which have an executable openmbv, mbsimgui, ...

The docker build cannot link with any lib from your local system. The docker container can only access files inside of /home/leonardo/Software/mbsim-env-build but no other files from your local system.

Can you cd to an xml example e.g. xml/hierarchical_modelling and execute mbsimxml or cd to xmlflat/hierarchical_modelling and execute mbsimflatxml? These are none UI program and should be less problematic.

Is your user id 1000? (id -u)

Can you check also the following:
- add `-e LOGNAME=dockeruser \` after the line `-e HOME=/tmp/home \` in `mbsim-env-build/build/docker/buildScripts/mbsbd`
- add `-e USER=dockeruser \` after the line `-e HOME=/tmp/home \` in `mbsim-env-build/build/docker/buildScripts/mbsbd`
- add both

The error may be cause by some dbus tools installed on your machine which I do not have. I will need some time to check this.
(running GUI program inside of docker is not really the intend of docker and needs some hacks. I have done such hacks in mbsbd but these may not work on all system. That may be a reason that GUI program are not running but e.g. mbsimxml should work (hopefully) without problems)

**Comment by leo-bart** [comment]
Yes, my user number is 1000.

I tested the three options you gave me, but none o them worked.

I believe you are right about the problem being related to GUI: the command line applications are working fine on the examples.

I tried to build the docker image precisely because the GUI programs (specifically openmbv and mbsimgui) are rendering transparent backgrounds for me:
![image](https://user-images.githubusercontent.com/18699508/81300516-2755ba80-904e-11ea-8004-84186fe0b6c9.png)

so I was hoping that tweaking some source code I could solve this. I think it is a Linux kernel problem, because when I was using Ubuntu 16.04 everything was fine. A moved to OpenSUSE 15 and later to Ubuntu 18.04 and on both the transparent background appear. I know this issue should be posted on the mbsim GitHub: I'm just informing this to justify why I was trying to run the GUI programs.

Thank you for the guidance so far.

**Comment by foerg** [comment]
I have the same problem with the Linux64 Release Build build from the build system when display compositing is enabled in the window manager (xfce4). Disabling it solves the problem. 
When I build MBSim from source the problem does not exist at all. I guess it has to do with either the version or the configuration of the Coin3D library.

**Comment by friedrichatgc** [comment]
Yes, I also know the problem with the transparency. I googled this about a year before and found that this is due to a bug in some X11 version of the OS in the transparency handling of the display compositor. As @foerg already noted a workaround is to disable the display compositing in the display configuration of your local system. How to disable this highly depends on your desktop environment XFCE, KDE, Gnome, ...
Since this bug is more than a year old it seems not to get fixed in CentOS7, the OS the docker image and the build system uses. So I don't see a clean solution for this next.

**Comment by friedrichatgc** [comment]
Can you try to add `--security-opt seccomp=unconfined \` in mbsbd, at the same place as the `-e ...` command before. This disables some docker security features so it's just to test if this helps.
I found several places that this problem relates to a problem with ubuntu and the docker version skipped with ubuntu e.g. https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1774739

**Comment by leo-bart** [comment]
Concerning the window transparency, turning compositing off really worked. Thank you. I couldn't find how to do that in GNOME (apparently, the Mutter window manager has very limited configuration options), but I installed xfce and now the visualization is fine.



> 
> 
> Can you try to add `--security-opt seccomp=unconfined \` in mbsbd, at the same place as the `-e ...` command before. This disables some docker security features so it's just to test if this helps.
> I found several places that this problem relates to a problem with ubuntu and the docker version skipped with ubuntu e.g. https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1774739

I will try to do that as soon as possible. For some weird reason, installing xfce alongside my old Ubuntu installation caused me some login problems and I had to reinstall the OS from scratch, so I have not had the time to recompile everything again.

**Comment by leo-bart** [comment]
Hello all! Getting back to this issue after a while just to confirm that a modified version of @friedrichatgc 's solution is a workaround (at least for Ubuntu).

Adding `--security-opt apparmor:unconfined` to  `./build/docker/buildScripts/mbsbd` solves the problem with the dbus connection and allow the GUI apps to open.
